#!/usr/bin/env python
import time
import sys

def runme(t):
    print 'I am going to sleep for %d seconds' % t
    time.sleep(t)
    print 'I am awake'

if __name__ == '__main__':
    t = int(sys.argv[1])
    runme(t)
